
export interface ProcessOptions {
  maintainAspectRatio: boolean;
  
  // Advanced Editing / Anti-detection features
  zoomLevel: number; // -0.5 to 0.5 (-50% to +50%)
  flipHorizontal: boolean;
  speed: number; // 0.5 to 2.0
  volume: number; // 0 to 2.0
  colorFilter: 'none' | 'bright' | 'warm' | 'cool' | 'contrast' | 'vintage';
  enableMotionBlur: boolean; // Toggle for motion blur effect
  
  // Visual Effects (New)
  filmGrainScore: number; // 0 to 1.0 (Strength of noise)
  enableVignette: boolean; // Darken corners
  enableAutoReorder: boolean; // Auto chop and reorder segments

  // New Pro Features
  trimStart: number; // seconds
  trimEnd: number; // seconds (0 means end of video)
  
  textOverlay: {
    enabled: boolean;
    text: string;
    position: number; // Percentage 0-100 (Y-axis)
    fontSize: number; // px
    backgroundColor: string; // Hex
    textColor: string; // Hex
  };
  
  // Export Settings
  resolution: '720p' | '1080p';
}

export type ProcessingStatus = 'idle' | 'fetching' | 'queued' | 'processing' | 'completed' | 'error';

export interface VideoItem {
  id: string;
  file: File | null;
  originalUrl: string | null; // The Shopee URL or Blob URL
  sourceType: 'file' | 'url';
  status: ProcessingStatus;
  progress: number;
  resultUrl: string | null;
  extension?: string; // New field to store the actual extension (mp4 or webm)
  errorMsg?: string;
  name: string;
  duration?: number; // Store duration for trimming UI
  productTitle?: string; // Extracted from Shopee link
  generatedCaption?: string; // Generated by AI
  generatedHook?: string; // Short viral hook for overlay
  generatedSubtitles?: string[]; // 3-5 lines of subtitles
  isGeneratingCaption?: boolean;
}

export interface ImageState {
  file: File | null;
  url: string | null;
}
